### ISSUE TITLE
Question: OSRS Gamesense

### ISSUE THREAD

**Issue by Osamu01** [LowieN-1848537/SteelseriesGamesense#13]
I'm curious if I can configure it to light up for more than just one game event?

**Comment by LowieN-1848537** [comment]
As far as i know you can assign a game event (eg health/ prayer) to a key (or a row) you should be able to have multiple different events displayed on the same keyboard.

If u mean as in having multiple events on the same key afaik this is not possible on steelseries keyboards. Unless they changed it recently which i see as unlikely

I hope this answers your question. Else i'm gonna need a bit more clarification as to what you mean exactly.
